# docker build -t secretsanta -f dockerfile .
# docker stack deploy -c application.yml app

# docker stack rm app

version: '3.7'

services:
  web:
    image: secretsanta
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    networks:
      - local_agent_network
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  migrations:
    image: secretsanta
    command: sh -c "python manage.py migrate && python create_superuser.py"
    volumes:
      - .:/code
    networks:
      - local_agent_network
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=dsb00715@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=MGrBcDOnxAq0

networks:
  local_agent_network:
    external: true